import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MobileProvider } from "~/contexts/mobile-context";
import { Toaster } from "~/components/ui/sonner";
import { TRPCProvider } from "~/trpc/client";
import { SessionRefresher } from "~/components/session-refresher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TRPCProvider>
          <MobileProvider>
            {children}
            {/* <InstallationProvider>{children}</InstallationProvider> */}
            <Toaster />
          </MobileProvider>
        </TRPCProvider>
        <SessionRefresher />
      </body>
    </html>
  );
}
